#cloud-config

hostname: coreos1
 
coreos:

  units:
    - name: etcd2.service
      command: start
    - name: systemd-networkd.service
      command: stop
    - name: static.network
      runtime: true
      content: |
        [Match]
        Name=enp0s3
 
        [Network]
        Address=192.168.56.101/24
        Gateway=192.168.56.2
        DNS=8.8.8.8
    - name: systemd-networkd.service
      command: start

  etcd2:
    name: "node01"
    discovery: https://discovery.etcd.io/a6feb79bba37018db74593d72c7c2d57
    advertise-client-urls: http://192.168.56.101:2379
    initial-advertise-peer-urls: http://192.168.56.101:2380
    listen-client-urls: http://0.0.0.0:2379
    listen-peer-urls: http://192.168.56.101:2380

users:
  - name: admin
    passwd: $1$vT0CWi8J$OfW5qpjVZYVnLrp7HEm4v0
    groups:
      - sudo
      - docker
