#cloud-config

hostname: coreos1
 
coreos:

  units:
    - name: etcd2.service
      command: start
    - name: systemd-networkd.service
      command: stop
    - name: static.network
      runtime: true
      content: |
        [Match]
        Name=enp0s3
 
        [Network]
        Address=192.168.56.101/24
        Gateway=192.168.56.2
        DNS=8.8.8.8
    - name: systemd-networkd.service
      command: start

  etcd2:
    name: "node01"
    advertise-client-urls: http://$public_ipv4:2379
    initial-advertise-peer-urls: http://$private_ipv4:2380
    listen-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001
    listen-peer-urls: http://$private_ipv4:2380,http://$private_ipv4:7001
    discovery: https://discovery.etcd.io/3073b8787885637e7d49d0ab4bbc2d7b
  fleet:
    public-ip: "$public_ipv4"
  flannel:
    interface: "$public_ipv4"
  units:
  - name: etcd2.service
    command: start
  - name: fleet.service
    command: start
  - name: flanneld.service
    drop-ins:
    - name: 50-network-config.conf
      content: |
        [Service]
        ExecStartPre=/usr/bin/etcdctl set /coreos.com/network/config '{ "Network": "10.1.0.0/16" }'
    command: start
  - name: docker-tcp.socket
    command: start
    enable: true
    content: |
      [Unit]
      Description=Docker Socket for the API

      [Socket]
      ListenStream=2375
      Service=docker.service
      BindIPv6Only=both

      [Install]
      WantedBy=sockets.target

users:
  - name: admin
    passwd: $1$vT0CWi8J$OfW5qpjVZYVnLrp7HEm4v0
    groups:
      - sudo
      - docker
